---
language: php
php:
 - 5.4
 - 5.5
 - 5.6
 - 7
 - hhvm
install:
 - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then printf "\n" | pecl install imagick; fi
 - if [ "$TRAVIS_PHP_VERSION" == 'hhvm' ]; then PHPINI=/etc/hhvm/php.ini; echo "hhvm.enable_zend_compat = true" >> $PHPINI; fi
 - composer install --prefer-source --dev --no-interaction
 - sudo apt-get install -y imagemagick
before_script:
 - mkdir -p media/thumbs/
 - cp tests/travis/settings.inc.travis settings.inc
 - cp tests/travis/orange_slice16.png media/
 - mysql -e 'create database jvo_test;'
 - cd tools
 - php dbimport.php ../sql/tables.sql
 - php dbimport.php ../tests/travis/travis.sql
 - cd ..
script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
  - vendor/bin/test-reporter
matrix:
  allow_failures:
    - php: hhvm
    - php: 7
addons:
 code_climate:
  repo_token: 473ed57db596678b2651bb88d7d33e0f559ae503b669a23163beb9050964d78a