---
language: php
php:
 - 5.4
 - 5.5
 - 5.6
 - hhvm
before_script:
 - mkdir -p media/thumbs/

 - printf "\n" | pecl install imagick
 - composer self-update
 - composer install --prefer-source --dev --no-interaction
 - cp tests/travis/settings.inc.travis settings.inc
 - cp tests/travis/orange_slice16.png media/
 - mysql -e 'create database jvo_test;'
 - cd tools
 - php dbimport.php ../sql/tables.sql
 - php dbimport.php ../tests/travis/travis.sql
 - cd ..
script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
matrix:
  allow_failures:
    - php: hhvm
 